name: Build and test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt install ninja-build
    - name: CMake
      run: mkdir build && cd build && cmake -GNinja ..
    - name: Build
      run: cmake --build build
    - name: TestVersion
      run: cd tests && ./test-versions.sh
    - name: version-gcc
      run: cd tests/version-gcc && ./test.sh
    - name: version-g++
      run: cd tests/version-g++ && ./test.sh
