name: ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt install ninja-build
    - name: Install Python packages
      run: pip install pytest numpy
    - name: CMake
      run: mkdir build && cd build && cmake -GNinja -DSOLD_PYBIND_TEST=ON ..
    - name: Build
      run: cmake --build build
    - name: Test
      run: cd build && ctest --output-on-failure
